apiVersion: v1
kind: Service

metadata:
  name: web-app

spec:
  selector:
    app: web-app

  ports:
    - name: http
      port: {{ .Values.webApp.service.port }}
      targetPort: {{ .Values.webApp.service.targetPort }}
