apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app
  namespace: login-crud

spec:
  ingressClassName: traefik

  rules:
  - host: login.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-app
            port:
              number: 80
