apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: login-crud
type: Opacque
stringData:
  MYSQL_ROOT_PASSWORD: SuperSecretRootPass
  MYSQL_USER: crud_user
  MYSQL_PASSWORD: CrudUserPass
  MYSQL_DATABASE: crud_links
