apiVersion: v1
kind: Service

metadata:
  name: link-service

spec:
  selector:
    app: link-service

  ports:
    - name: http
      port: {{ .Values.linkService.service.port }}
      targetPort: 3001
